---
title: "42.7"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
---


<object data="topik/todaysfinan/chapter/chapter42/pdf42finan/Todays_Finan_42_7.pdf" type="application/pdf" width="100%" height="100%" style="min-height:100vh;">
    <p>It appears you don't have a PDF plugin for this browser.
    No biggie... you can <a href="https://github.com/AgungSudanta/Daily-Mabar/blob/main/topik/todaysfinan/chapter/chapter42/pdf42finan/Todays_Finan_42_7.pdf">click here to download the PDF file.</a></p>
</object>

Tes tex to HTML converter
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>TodayFinan42-7</title>
  <style>
    html {
      color: #1a1a1a;
      background-color: #fdfdfd;
    }
    body {
      margin: 0 auto;
      max-width: 36em;
      padding-left: 50px;
      padding-right: 50px;
      padding-top: 50px;
      padding-bottom: 50px;
      hyphens: auto;
      overflow-wrap: break-word;
      text-rendering: optimizeLegibility;
      font-kerning: normal;
    }
    @media (max-width: 600px) {
      body {
        font-size: 0.9em;
        padding: 12px;
      }
      h1 {
        font-size: 1.8em;
      }
    }
    @media print {
      html {
        background-color: white;
      }
      body {
        background-color: transparent;
        color: black;
        font-size: 12pt;
      }
      p, h2, h3 {
        orphans: 3;
        widows: 3;
      }
      h2, h3, h4 {
        page-break-after: avoid;
      }
    }
    p {
      margin: 1em 0;
    }
    a {
      color: #1a1a1a;
    }
    a:visited {
      color: #1a1a1a;
    }
    img {
      max-width: 100%;
    }
    svg {
      height: auto;
      max-width: 100%;
    }
    h1, h2, h3, h4, h5, h6 {
      margin-top: 1.4em;
    }
    h5, h6 {
      font-size: 1em;
      font-style: italic;
    }
    h6 {
      font-weight: normal;
    }
    ol, ul {
      padding-left: 1.7em;
      margin-top: 1em;
    }
    li > ol, li > ul {
      margin-top: 0;
    }
    blockquote {
      margin: 1em 0 1em 1.7em;
      padding-left: 1em;
      border-left: 2px solid #e6e6e6;
      color: #606060;
    }
    code {
      font-family: Menlo, Monaco, Consolas, 'Lucida Console', monospace;
      font-size: 85%;
      margin: 0;
      hyphens: manual;
    }
    pre {
      margin: 1em 0;
      overflow: auto;
    }
    pre code {
      padding: 0;
      overflow: visible;
      overflow-wrap: normal;
    }
    .sourceCode {
     background-color: transparent;
     overflow: visible;
    }
    hr {
      background-color: #1a1a1a;
      border: none;
      height: 1px;
      margin: 1em 0;
    }
    table {
      margin: 1em 0;
      border-collapse: collapse;
      width: 100%;
      overflow-x: auto;
      display: block;
      font-variant-numeric: lining-nums tabular-nums;
    }
    table caption {
      margin-bottom: 0.75em;
    }
    tbody {
      margin-top: 0.5em;
      border-top: 1px solid #1a1a1a;
      border-bottom: 1px solid #1a1a1a;
    }
    th {
      border-top: 1px solid #1a1a1a;
      padding: 0.25em 0.5em 0.25em 0.5em;
    }
    td {
      padding: 0.125em 0.5em 0.25em 0.5em;
    }
    header {
      margin-bottom: 4em;
      text-align: center;
    }
    #TOC li {
      list-style: none;
    }
    #TOC ul {
      padding-left: 1.3em;
    }
    #TOC > ul {
      padding-left: 0;
    }
    #TOC a:not(:hover) {
      text-decoration: none;
    }
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    /* The extra [class] is a hack that increases specificity enough to
       override a similar rule in reveal.js */
    ul.task-list[class]{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      font-size: inherit;
      width: 0.8em;
      margin: 0 0.8em 0.2em -1.6em;
      vertical-align: middle;
    }
    .display.math{display: block; text-align: center; margin: 0.5rem auto;}
  </style>
</head>
<body>
<p>Matematika Keuangan 2 Section 42 No 42.7<br />
Andhika N. (6 Feb 2025)</p>
<div class="problem">
<p><strong>Problem 1</strong>. <em>A 20 year bond matures for its par
value of 10,000. The coupon payable semi-annually is 400. Calculate the
price of the bond at a 6% yield rate convertible semi-annually.</em></p>
</div>
<div class="Solution">
<p><strong>Solution 1</strong>. <em>Diketahui:<br />
</em></p>
<ul>
<li><p><em>F = 10,000</em></p></li>
<li><p><em>Kupon Semi-annual (semesteran) sebesar 400 <span
class="math inline"> ⟹ <em>F</em> × <em>r</em> = 400</span></em></p></li>
<li><p><em>yield rate convertible semi annually <span
class="math inline"> ⟹ <em>i</em><sup>(2)</sup> = 6%⟹</span> yield rate
efektif semesteran (dinotasikan i di jawaban ini): <span
class="math inline">$i = \frac{i^{(2)}}{2} = 3\% =
0.03$</span></em></p></li>
<li><p><em>20 tahun dengan kupon semesteran <span
class="math inline"> ⟹ <em>n</em> = 20 × 2 = 40</span></em></p></li>
<li><p><em>C = F = 10,000 (tidak diberitahu, berarti asumsikan sama
dengan Face Value)</em></p></li>
</ul>
<p><em>Ditanya: Harga dari obligasi<br />
Jawab:<br />
<span class="math display">$$\begin{aligned}
    P &amp;= F \times r \times \ax{\angl{n}i} +  C \times v_{i}^{n}\\
    &amp;= (F \times r) \times \ax{\angl{40}3\%} + C \times
v_{3\%}^{40}\\
    &amp;= 400 \times \frac{1-v^{40}}{i} + 10,000 \times v_{3\%}^{40}\\
    &amp;= 400 \times \frac{1-(1.03)^{-40}}{0.03} + 10,000 \times
{(1.03)}^{-40}\\
    &amp;=12,311.4772 \approx 12,311.48
\end{aligned}$$</span></em></p>
</div>
</body>
</html>

