---
title: "10.4"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    smooth-scroll: true

---

Explain why the sample mean may not be a consistent estimator of the population mean for a Pareto distribution. 

**Answer**

By definition, an estimator is (weakly) consistent if it satisfies the following con
dition:\\

Let $\hat{\theta_n}$ be an estimator of $\theta$, if $\forall \delta > 0$ and any $\theta$, $\lim_{n \to \infty} Pr(  \lvert \hat{\theta_n} - \theta \rvert > \delta) = 0$, then $\hat{\theta_n}$ is a (weakly) consistent estimator of $\theta$.\\

Aside from definition, we can try to prove that the sample mean may not be a consistent estimator of the population mean for a Pareto distribution using the following theorem:\\

If $\lim_{n \to \infty} E[\hat{\theta_n}] = \theta $ and $\lim_{n \to \infty} Var[\hat{\theta_n}] = 0 $, then $\hat{\theta_n}$ is (weakly) consistent.\\

The expectation and variation of a Pareto distribution with parameter $(\alpha, \theta)$ are (with $\alpha \geq 1 \cap 2)$:\\

\begin{align}
    E[X] = \frac{\theta}{\alpha-1}\\
    Var[X] = \frac{\theta^2 \times \alpha}{ {(\alpha-1)}^2 \times (\alpha-2) }
\end{align}

We can immediately answer the question without using the above definition nor theorem (we may do so anyway later) and without involving the more complicated form of the expectation and variation of a Pareto distribution, observe that, if $\alpha = 1$, the expectation would not exist, thus it is impossible for the sample mean, which will always exist to accurately estimate it.\\

If we go to the \href{https://en.wikipedia.org/wiki/Pareto_distribution}{Pareto Wikipedia} page for Pareto distribution, we can also see that if $\alpha <=1$, then the mean for the Pareto distribution would not exist, thus if we only use the sample mean, which does not account for the value of $\alpha$ and will always exist, we cannot accurately estimate the mean for the Pareto distribution.\\

**Other Answer**
If we do not know the value of $\alpha$, then if $\alpha \leq 1$, we can see that:
\begin{align*}
    \lim_{n \to \infty} E[\hat{\theta_n}] &= \lim_{n \to \infty} E[\theta]\\
    &= \infty
\end{align*}
which is an inconclusive form and thus the limit does not exist and we cannot use the theorem to always prove that the mean sample is a (weakly) consistent estimator of a Pareto distribution mean.\\

With the Chebyshev equation, that is $Pr( \lvert X - \mu \rvert \geq k\sigma) \leq \frac{1}{k^2}$ and the definition of (weakly) consistent estimator, choose $ k = \frac{\delta \sqrt{n} }{ \sqrt{Var[\hat{\theta_n}} ] } \implies \frac{1}{k^2} = \frac{Var[\hat{\theta_n}] }{ \delta^2 n }$\\

Let $\mu$ be the mean of a pareto distribution, then:
\begin{align*}
    Pr( \lvert X - \mu \rvert \geq k\sigma) \leq \frac{1}{k^2} &= Pr( \lvert \hat{\theta_n} - \mu \rvert \geq \frac{\delta \sqrt{n}{ \sqrt{Var[\hat{\theta_n}]} }} {\sqrt{Var[\hat{\theta_n}]}} )\leq \frac{Var[\hat{\theta_n}] }{ \delta^2 n }\\
    &= Pr( \lvert \hat{\theta_n} - \mu \rvert )\geq
\end{align*}





