---
title: "5.3.12"
format:
    html:
        theme:
            light: flatly
            dark: darkly
        css: styles.css
        toc: true
---

Let $I := [0, \frac{\pi}{2}]$ and let $f : I \to \mathbb{R}$ be defined by $f(x) := \sup\{x^2, \cos x\}$ for $x \in I$. Show there exists an absolute minimum point $x_0 \in I$ for $f$ on $I$. Show that $x_0$ is a solution to the equation $\cos x = x^2$

Answer

It will be shown that $\exists x_0 \in I \ni f(x_0) \leq f(x) \; \forall x \in I$, and then show that $\cos x_0 = x_0^2$

Let $g:I \to \mathbb{R}$ and $h : I \to \mathbb{R}$ be defined by $g(x) := x^2$ and $h(x) := \cos x$ which can be proven continuous on $I$. Now let $k(x) := g(x) - h(x)$ which also continuous on $I$, notice that $k(0) = 0 - 1 < 0$ and $k(\frac{\pi}{2}) > 0$ because $\cos x \leq x^2 \; \forall x \geq 1$. Therefore by Location of Roots Theorem $\exists x_1 \in I \ni g(x_1) = h(x_1)$. This implies that $\exists x_1 \in I \ni x^2 < \cos x \; \forall x < x_1$ because $x_1$ is the only root for $k$ on $I$.

Thus we can define $f$ as $$f(x) = \begin{cases}
    \cos x & 0 \leq x < x_1 \\
    x^2 & x_1 \leq x \leq \frac{\pi}{2}
\end{cases}$$

This implies that $f$ continuous, thus there must be absolute minimum point $x_0$ for $f$ on $I$.

Thus $g$ have absolute minimum point $x_0$ on $[0, x_1)$ say $c_1$, and $h$ have absolute minimum point $x_0$ on $[x_1, \frac{\pi}{2}]$ say $c_2$, which can be proven that $c_1 = c_2$. Therefore $c_1 = \cos x_0 = x_0^2 = c_2$