---
title: "5.3.3"
format:
    html:
        theme:
            light: flatly
            dark: darkly
        css: styles.css
        toc: true
---

Let $I := [a,b]$ and let $f : I \to \mathbb{R}$ be a continuous function on $I$ such that for each $x$ in $I$ there exist $y$ in $I$ such that $|f(y)| \leq \frac{1}{2}|f(x)|$. Prove there exist a point $c$ in $I$ such that $f(c) = 0$

Answer 

It will be shown that there exist a point $c$ in $I$ such that $f(c) = 0$

Because for any $x \in I$ the inequality $|f(y)| \leq \frac{1}{2}|f(x)|$ is true, then we have the following

\begin{align*}
    |f(y_0)| & \leq \frac{1}{2}|f(x)| \\
    |f(y_1)| & \leq \frac{1}{2}|f(y_0)|  \leq \frac{1}{2^2}|f(x)|\\
    .\\
    .\\
    .\\
    |f(y_n)| & \leq \frac{1}{2}|f(y_{n-1})| \leq \frac{1}{2^n+1}|f(x)|
\end{align*}

Thus we can construct a sequence $|y| = (|f(y_n)|)$ which has a property that it is monotonically decreasing sequence. By definition of absolute value, infimum of $\{|y_n| : n \in \mathbb{N}\}$ is equal to 0. Thus from Monotone Convergence Theorem $\lim |f(y_n)| = 0$. From property of continuity function, $|f|$ also continuous because $f$ continuous thus $|f(c)| = 0$ which implies $f(c) = 0$

$\therefore \exists c \in I \ni f(c) = 0$