---
title: "5.6.6"
format:
    html:
        theme:
            light: flatly
            dark: darkly
        css: styles.css
        toc: true
---

Let $I \subseteq \mathbb{R}$ be an interval and let $f : I \to R$ be increasing on $I$. Suppose that $c \in I$ is not an endpoint of $I$. Show that $f$ is continuous at $c$ if and only if there exists a sequence $(x_n)$ in $I$ such that $x_n < c$ for $n = 1, 3, 5, . . . ; x_n > c$ for $n = 2, 4, 6, . . . ;$ and such that $c = \lim(x_n)$ and
$f (c) = \lim ( f (x_n))$

Answer

It will be shown that if $f$ is continuous at $c$, then there exists a sequence $(x_n)$ in $I$ such that $x_n < c$ for $n = 1, 3, 5, . . . ; x_n > c$ for $n = 2, 4, 6, . . . ;$ and such that $c = \lim(x_n)$ and $f (c) = \lim ( f (x_n))$

$c$ is not an endpoint of $I$, then by theorem $$\displaystyle{\lim_{x \to c^-}} \; f = f(c) = \displaystyle{\lim_{x \to c^+}} \; f$$

By sequential criteria, then there exists $(y_n)$ and $(z_n)$ in $I$ that converge to $c$ such that it satisfy $y_n \leq c$ and $z_n \geq c$ for all $n \in \mathbb{N}$. 

Let $(x_k)$ with $x_{2k} = y_k$ and $x_{2k-1} = z_k$ for all $k \in \mathbb{N}$. This sequence converge to $C$ because any subsequence of $(x_k)$ converge to $c$, thus $\lim(f(x_k)) = f(c)$

It will be shown that if there exists a sequence $(x_n)$ in $I$ such that $x_n < c$ for $n = 1, 3, 5, . . . ; x_n > c$ for $n = 2, 4, 6, . . . ;$ and such that $c = \lim(x_n)$ and $f (c) = \lim ( f (x_n))$, then $f$ is continuous at $c$

$(x_n)$ converge to $c$, then any subsequence of $(x_n)$ also converge to $c$ by theorem. Let $(y_n)$ and $(z_n)$ be subsequence of $(x_n)$ where $y_n = x_{2n-1}$ and $z_n = x_{2n}$. 

Because $f(c) = \lim ( f (x_n))$, then it must follow that $f(c) = \lim(f(y_n)) = \lim(f(z_n))$ because $(y_n)$ and $(z_n)$ are a subsequence of $(x_n)$. Notice that $y_n < c < z_n \; \forall n \in \mathbb{N}$, thus by definition $\displaystyle{\lim_{x \to c^-}} \; f = f(c)$ and $f(c) = \displaystyle{\lim_{x \to c^+}} \; f$ which implies that $$\displaystyle{\lim_{x \to c^-}} \; f = f(c) = \displaystyle{\lim_{x \to c^+}} \; f$$
Therefore by theorem $f$ continuous at $c$