---
title: "47.13"
author: "GD"
date: last-modified

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
---

<a href="https://github.com/AgungSudanta/Daily-Mabar/blob/main/topik/todaysfinan/chapter/chapter47/PdfFinan47/Todays_Finan_47_13.pdf">PDF version of this answer (may be slightly different)</a>


A $1000$ par value bond pays annual coupons of $80$. The bond is redeemable at par in $30$ years, but is callable any time from the end of the 10th year at $1050$.

Based on her desired yield rate, an investor calculates the following potential purchase prices, $P$ :

- Assuming the bond is called at the end of the 10th year, P = 957

- Assuming the bond is held until maturity, P = 897

The investor buys the bond at the highest price that guarantees she will receive at least her desired yield rate regardless of when the bond is called. The investor holds the bond for 20 years, after which time the bond is called.

Calculate the annual yield rate the investor earns.

**Answer**

We have

- $F = 1000$

- $F \cdot r = 80$

- $n = 30$ years, callable from $t = 10$

- $C = 1050$, given called at $t=10$

Let $i$ be the annual yield rate of a 

Solving for the yield rate given the bond is called at $t=10$,

\begin{align*}
P &= F\cdot r \cdot a_{\enclose{actuarial}{n}i} + C \cdot v_i^n\\
957 &= 80 \cdot \left( \frac{1-(1+i)^{-10}}{i}   \right) + 1050 \cdot (1+i)^{-10}\\
i &= 0.0899911
\end{align*}

Solving for the yield rate given the bond is called at maturity,

\begin{align*}
P &= F\cdot r \cdot a_{\enclose{actuarial}{n}i} + C \cdot v_i^n\\
897 &= 80 \cdot \left( \frac{1-(1+i)^{-30}}{i}   \right) + 1000 \cdot (1+i)^{-30}\\
i &= 0.0900281
\end{align*}

Thus, the desired yield rate is $0.0899911\%$

We have $r = 80/1000 = 8\% < i$, thus it is a discount case where the issuer would hold the bond as long as possible. Thus, the highest price that guarantees the desired yield rate will be received is $897$

However, since the bond was called at $t=20$,

\begin{align*}
P &= F\cdot r \cdot a_{\enclose{actuarial}{n}i} + C \cdot v_i^n\\
897 &= 80 \cdot \left( \frac{1-(1+i)^{-20}}{i}   \right) + 1000 \cdot (1+i)^{-20}\\
i &= 0.0924304
\end{align*}


$\therefore i \approx 9.24\%$
